@startuml

[*] --> Bootstrap
Bootstrap -right-> Initialization
Initialization -right-> Collection
Collection --> TestRunning
TestRunning -left-> Reporting
Reporting -left-> [*]

Bootstrap: Load "early" plugins\nparse command line command\nload config
Initialization: Register options and plugins\nStart test session
Collection: Collecting test files with test functions/methods\nParametrization of tests
TestRunning: Calculating and teardown of fixtures\nRunning tests :)
Reporting: Generate report[s]
@enduml